live_config_reload = true

[colors]
transparent_background_colors = false

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "Hasklug Nerd Font"

[font.offset]
x = 0
y = 4

[window]
opacity = 1.0

[window.dimensions]
columns = 160
lines = 40
